MVC_Company/Demo/Controllers/DepartmentController.cs
using MVC_Demo.BLL.Interfaces;
using MVC_Demo.BLL.Repositories;
using Microsoft.AspNetCore.Mvc;
using MVC_Demo.DAL.Models;
using Demo.BLL.Interfaces;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace MVC_Demo.PL.Controllers
{
	//[AllowAnonymous]
	[Authorize]
	public class DepartmentController : Controller
    {
        //private readonly IDepartmentRepository _departmentRepository;
        private readonly IUnitOfWork _unitOfWork;

        public DepartmentController(/*IDepartmentRepository departmentRepository*/ IUnitOfWork unitOfWork)  // Ask CLR Create Object from IDepartmentRepository
        {
            //this._departmentRepository = departmentRepository;
            _unitOfWork = unitOfWork;
        }

        // /Department/Index
        public async Task<IActionResult> Index()
        {

            //var dept = _departmentRepository.GetAll();
            var dept = await _unitOfWork.DepartmentRepository.GetAll();

            return View(dept);
        }


        // /Department/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department model)
        {
            if (ModelState.IsValid)  // Server Side Validation
            {
                //int Count= _departmentRepository.Add(model);
                //int Count = _unitOfWork.DepartmentRepository.Add(model);
                _unitOfWork.DepartmentRepository.Add(model);
                var Count = await _unitOfWork.Complete();


                if (Count > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View();
        }


        public async Task<IActionResult> Details(int? id, string ViewName = "Details") 
        {
            if (id is null)
                return BadRequest();   //400 ERROR

            //var department = _departmentRepository.Get(id.Value);
            var department = await _unitOfWork.DepartmentRepository.Get(id.Value);


            if (department is null)
                return NotFound();  //404 

            return View(ViewName, department);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
        }
        /*public IActionResult Edit(int? id)
        {
            if (id is null)
                return BadRequest();   //400 ERROR

            var department = _departmentRepository.Get(id.Value);

            if (department is null)
                return NotFound();  //404 
             
            return View(department);
        }*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id,Department model)
        {
            if(id !=model.Id)
                return BadRequest();  //400

            if (ModelState.IsValid)   // Server Side Validation
            {
                //var count = _departmentRepository.Update(model);
                //var count = _unitOfWork.DepartmentRepository.Update(model);
                _unitOfWork.DepartmentRepository.Update(model);

                int count = await _unitOfWork.Complete();


                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }
        /* public IActionResult Delete(int? id)
         {
             if (id is null)
                 return BadRequest();   //400 ERROR

             var department = _departmentRepository.Get(id.Value);

             if (department is null)
                 return NotFound();  //404 

             return View(department);
         }*/

        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int? id, Department model)
        {
            if (id != model.Id)
                return BadRequest();  //400

            if (ModelState.IsValid)   // Server Side Validation
            {
                //var count = _departmentRepository.Delete(model);
                //var count = _unitOfWork.DepartmentRepository.Delete(model);
                _unitOfWork.DepartmentRepository.Delete(model);
                int count = await _unitOfWork.Complete();


                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }
    }
}

MVC_Company/Demo/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IMapper mapper;
        private readonly UserManager<ApplicationUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper,UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.mapper = mapper;
            this.userManager = userManager;
        }
        public IActionResult Index(string seachr)
        {
            var dbrole = roleManager.Roles;

            var roles = dbrole.Select(r => new RoleViewModel() { Id = r.Id, Name = r.Name });
            if (!string.IsNullOrEmpty(seachr))
                roles = dbrole.Where(r => r.NormalizedName.Contains(seachr.ToUpper())).Select(r => new RoleViewModel() { Id = r.Id, Name = r.Name });
            ViewData["search"] = seachr;
            return View(roles);
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByNameAsync(model.Name);
                if (role is null)
                {
                    role = new IdentityRole() { Name = model.Name };
                    var result = await roleManager.CreateAsync(role);
                    if (result.Succeeded) return RedirectToAction(nameof(Index));
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);

                    return View(model);

                }
                ModelState.AddModelError(string.Empty, "Role Already Exist");
                return View(model);
            }
            return View(model);
        }

        public async Task<IActionResult> Details(string id, string viewname = "Details")
        {
            var dbrole = await roleManager.FindByIdAsync(id.ToString());
            var role = new RoleViewModel() { Id = dbrole.Id, Name = dbrole.Name };
            return View(viewname, role);
        }
        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole() { Name = model.Name, Id = model.Id };
                var result = await roleManager.UpdateAsync(role);
                if (result.Succeeded)
                    return RedirectToAction(nameof(Index));
                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

                return View(model);
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(model.Id.ToString());
                var result = await roleManager.DeleteAsync(role);
                if (result.Succeeded) return RedirectToAction(nameof(Index));
                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

                return View(model);
            }
            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if(role is null)
                return NotFound();


            ViewData["RoleId"] = roleId;



            var usersInRole = new List<UsersInRoleViewModel>();            
            var users = await userManager.Users.ToListAsync();

            foreach (var user in users)
            {
                var userInRole = new UsersInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };

                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected= false;
                }

                usersInRole.Add(userInRole);

            }
            return View(usersInRole);

        }


        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId,List<UsersInRoleViewModel> users)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await userManager.FindByIdAsync(user.UserId);
                    if(appUser is not null)
                    {
                        if (user.IsSelected && ! await userManager.IsInRoleAsync(appUser,role.Name))
                        {
                            await userManager.AddToRoleAsync(appUser,role.Name);
                        }
                        else if (!user.IsSelected && await userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await userManager.RemoveFromRoleAsync(appUser, role.Name);

                        }
                    }
                }

                return RedirectToAction(nameof(Edit), new { id = roleId });
            }
            return View(users);

        }
    }
}

MVC_Company/Demo/Controllers/UserController.cs
using AutoMapper;
using Demo.BLL;
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Demo.PL.Helper;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
	[Authorize]
	public class UserController : Controller
	{
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMapper mapper;

        public UserController(UserManager<ApplicationUser> userManager, IMapper mapper)
        {
            this.userManager = userManager;
            this.mapper = mapper;
        }


        public async Task<IActionResult> Index(string SearchInput)
        {
            var users = mapper.Map<IEnumerable<UserViewModel>>(await userManager.Users.Select(u => new UserViewModel()
            {
                Id = u.Id,
                UserName = u.UserName,
                Email = u.Email,
                //ImageUrl = u.ImageUrl,
                FirstName = u.FirstName,
                LastName = u.LastName,

            }).ToListAsync());
            if (SearchInput is not null)
                users = mapper.Map<IEnumerable<UserViewModel>>(await userManager.Users.Where(u => u.NormalizedEmail.Contains(SearchInput.ToLower())).Select(u => new UserViewModel()
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    Email = u.Email,
                    //ImageUrl = u.ImageUrl,
                    FirstName = u.FirstName,
                    LastName = u.LastName,

                }).ToListAsync());
            return View(users);
        }



        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();   //400 ERROR

            var user = await userManager.FindByIdAsync(id);
            
            if (user is null)
                return NotFound();  //404             

            var userr = new UserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,

            };


            return View(ViewName, userr);
       
        }




        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id,ViewName: "Edit");

        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = mapper.Map<ApplicationUser>(model);

                var result = await userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    TempData["Updated"] = $"{user.UserName} has been updated ";
                    return RedirectToAction("Index");
                }
                foreach (var item in result.Errors)
                    ModelState.AddModelError(string.Empty, item.Description);
                return View(model);
            }
            return View(model);
        }




        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByEmailAsync(model.Email);
                if (user is not null)
                {
                    var result = await userManager.DeleteAsync(user);
                    if (result.Succeeded)
                    {
                        TempData["message"] = $"{user.UserName} has been deleted";
                        return RedirectToAction(nameof(Index));
                    }
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, item.Description);
                    }

                    return View(model);
                }
                return View(model);

            }
            return View(model);
        }


    }
}

MVC_Company/Demo/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib @ViewData["Title"] Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/AuthStyle.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>



		@RenderBody();



		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@await RenderSectionAsync("Validation", required: false);
</html>

MVC_Company/Demo/Views/Shared/_ButtonPartialView.cshtml
@model string


<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i>
        Details
    </a>

</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i>
        Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-trash"></i>
        Delete
    </a>
</td>

MVC_Company/Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="index">Departments</a>

                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="index">Employees</a>

                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li>

                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li>

                            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignIn">Login</a>
                        </li>
                        <li>

                            <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li>

                            <a class="nav-link text-dark btn btn-danger ml-lg-5" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container>
            &copy; 2024 - Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Validation", required: false)

    @* @await RenderSectionAsync("Scripts", required: false) *@

</body>
</html>